### ISSUE TITLE
Attendance (Querying Analysis)

### ISSUE THREAD

**Issue by shahghasiadil** [shahghasiadil/Faculty-Management-System-KDRU#7]
Making Attendance for Students just let Admin to Select Semester , Period , Subject and after that print the Attendance of Specific class with Students

**Comment by Ehsan-sudo** [comment]
check the attendance related routes. if they work, i will close the issue. 
you can find some routes regarding student in the student controller as well.

**Comment by shahghasiadil** [comment]
@Ehsan-sudo please can you tell me or mention me the pull request that's you have done for it?
